### ISSUE TITLE
Stable tags for heroku/heroku:24 architecture variants

### ISSUE THREAD

**Issue by joshwlewis** [heroku/base-images#277]
Currently, we're producing `heroku/heroku:24` and `heroku/heroku:24-build` as a multi-arch images (OCI Image Manifests). You can see evidence of that [here](https://hub.docker.com/layers/heroku/heroku/24/images/sha256-ef63d62be65d145f7db1f11257691b294b5dcc302ffe14a33185884780572e1c?context=repo). This is convenient, as docker clients will generally select the most appropriate image for their local architecture. However, when trying to use an image for another architecture, there isn't a convenient way to reference other architecture images. 

For instance, I'm on an Intel-based mac, and I sometimes need to poke around with the `arm64` variant. When running`docker run --rm -it heroku/heroku:24`, my local client will generally prefer the `amd64` image. I can use the `--platform linux/arm64` option on that command, but not all docker commands support that (like say [`docker inspect`](https://docs.docker.com/reference/cli/docker/inspect/)). I've read that `DOCKER_DEFAULT_PLATFORM=linux/amd64` will also do this in some scenarios (maybe `docker build`?), but it seems inconsistent in my testing. This issue is also challenging with `pack builder create`, as it will also favor the local architecture. The most reliable method is instead to reference an image I know to be a `24-run` image for `arm64` by a checksum, like this: `heroku/heroku@sha256:ef63d62be65d145f7db1f11257691b294b5dcc302ffe14a33185884780572e1c`. But that's not very ergonomic or readable.

Should we be providing stable tags to make it easier to use a specific architecture? Maybe something like `heroku:24_arm64`, `heroku:24-build_amd64`, `heroku/heroku:24-build_arm64.nightly`, etc.? Or some other scheme?

**Comment by colincasey** [comment]
Seems like a reasonable workaround for cases where certain commands don't make it easy to reference a specific image from the image manifest. Any downsides to implementing this?

**Comment by edmorley** [comment]
I'm not against doing so (it would presumably mean we can drop the temporary tags thing too), though:
- I see the official Docker images don't do this (eg https://hub.docker.com/_/ubuntu/tags), so presumably this isn't an issue in practice for most workflows (I would imagine `--platform` does cover 95% of the workflows). (I have experienced the `docker inspect` thing, but I think that's because we're still at the kicking the tires stage; once things settle down we aren't really needing cross-arch image inspection)
- We'll have to figure out how to fit all these tags and permutations into the tags table in the README, which is already pretty crowded
- Once upstream CNB gains better multi-arch support (the RFC hasn't merged yet, which is why we have rough edges), it feels like one of the main reasons for needed these tags goes away (`pack builder create` missing `--platform` support)

We could always add the tags with the understanding that we remove them if we find them no longer necessary?

**Comment by joshwlewis** [comment]
`_linux-{arch}` tag suffixes like `heroku/heroku:24_linux-amd64` were added in #318 and are now available on Docker Hub.
