### ISSUE TITLE
ARM64 now available on GitHub Actions

### ISSUE THREAD

**Issue by boboldehampsink** [heroku/base-images#311]
FWIW - https://github.blog/2024-06-03-arm64-on-github-actions-powering-faster-more-efficient-build-systems/

**Comment by edmorley** [comment]
@boboldehampsink Hi! Is this a dupe of #194? It's not clear what this issue is asking for :-)

Note: We were part of GitHub's ARM runner private beta, so have been using their runners for a bit in various repos (eg the CNB repos and the CNB builder repo). Now that the runners are out officially, we're in the process of switching to them from the private runners.

**Comment by boboldehampsink** [comment]
It's just a heads up, good to know you guys already worked with the beta.
